/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {
//        Project project = new Project();
//        project.setName("Estudar para prova");
//        ProjectController.save(project);

//          project.setId(1);
//          project.setName("Dormir");
//          project.setDescription("Irei Dormir durante todo o dia");
//          ProjectController.update(project);
//        List<Project> result = ProjectController.getAll(2);
//        System.out.println(result.get(0).getName());
//
//        Task task = new Task();
//
//        task.setIdProject(2);
//        task.setName("Abrir o caderno");
//        
//        String dataStr = "2023-04-25";
//        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
//        Date data = formatter.parse(dataStr);
//        
//        String updated = "2023-04-25";
//        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
//        Date dataUpdate = formatter.parse(dataStr);
//        
//        
//        task.setUpdatedAt(Update);
//        task.setDeadline(data);
//        task.setIsCompleted(false);
//
//        TaskController.save(task);
    }
}
